version: "3.9"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=girder
    ports:
        - 27017:27017
  broker:
    image: rabbitmq:3.8
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - RABBITMQ_HOST=broker
    ports:
      - 6379:6379
  backend:
    build: ./backend
    depends_on:
      - mongo
      - broker
    environment:
      - MONGO_DATABASE=mongodb://mongo:27017/girder
    ports:
      - 8081:8080
    profiles:
      - demo
  frontend:
    build: ./frontend
    environment:
      - BACKEND_HOST=http://backend:8080
    depends_on:
      - backend
    ports:
      - 8080:8080
    profiles:
      - demo
