#!/usr/bin/env bash

trap "exit" INT TERM
trap '[[ -z "$(jobs -rp)" ]] || kill $(jobs -rp); wait' EXIT

GIT_ROOT=$(git rev-parse --show-toplevel)
BACKEND_ROOT="$GIT_ROOT/backend"
FRONTEND_ROOT="$GIT_ROOT/frontend"
DATA_ROOT="$GIT_ROOT/data"
MONGO_ROOT="$DATA_ROOT/mongo"
GIRDER_ROOT="$DATA_ROOT/girder"

alias girder="$BACKEND_ROOT/.venv/bin/girder"
alias vite="$FRONTEND_ROOT/node_modules/.bin/vite"

function deps() {
    (
        cd "$BACKEND_ROOT"
        tox -r --devenv .venv && girder build --dev
    ) 2>&1 | sed "s/^/$(tput setaf 3)[backend]  $(tput op)/" &
    (
        cd "$FRONTEND_ROOT"
        npm ci
    ) 2>&1 | sed "s/^/$(tput setaf 6)[frontend] $(tput op)/" &
}

function serve() {
    mkdir -p "$DATA_ROOT"
    mkdir -p "$MONGO_ROOT"
    mkdir -p "$GIRDER_ROOT"
    (
        mongod --dbpath "$MONGO_ROOT"
    ) 2>&1 | sed "s/^/$(tput setaf 8)[mongo]    $(tput op)/" &
    (
        girder serve --dev --host localhost
    ) 2>&1 | sed "s/^/$(tput setaf 3)[backend]  $(tput op)/" &
    (
        cd "$FRONTEND_ROOT"
        vite --clearScreen false --host localhost
    ) 2>&1 | sed "s/^/$(tput setaf 6)[frontend] $(tput op)/" &
}

$1
wait
